"""Alter phrase column length

Revision ID: dc797ae843ae
Revises: 
Create Date: 2024-07-05 19:24:39.471175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc797ae843ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('phrase', 'phrase', type_=sa.String(255))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('phrase', 'phrase', type_=sa.String(20))


    # ### end Alembic commands ###
